/* Autogenerated by png2wx.pl on Fri Oct 22 18:05:16 2010 */
#ifndef LOGO_HPP
#define LOGO_HPP 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap _img_vengeance;

#endif /* LOGO_HPP */
